# Building a model with KNN Classifier

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
atm = pd.read_csv(r'Dataset/ATM_Maintenance_Cleaned.csv', parse_dates=['Date'])
atm

,Date,ATM_ID,District,Location_Type,Manufacturer,ATM_Age_Yrs,Daily_Transactions,Failed_Transactions,Cash_Remaining_Pct,Cash_Loaded_Today,...,Memory_Usage_Pct,Network_Latency_ms,Network_Drops,UPS_Battery_Pct,Power_Outages_7D,Days_Since_Maintenance,Previous_Failures_90D,Customer_Complaints_7D,Failure_Code,Failure_Next_48H
0,2025-01-01,ATM058,Idukki,Hospital,NCR,1.2,429,15,69.0,0,...,52,46,0,78,2,29,4,1,5,1
1,2025-01-02,ATM173,Kozhikode,Railway,Diebold,1.9,343,6,43.0,0,...,45,10,0,92,3,58,1,0,2,1
2,2025-01-03,ATM187,Malappuram,Airport,Diebold,2.5,285,10,78.0,0,...,53,66,2,88,0,63,0,0,0,0
3,2025-01-04,ATM256,Alappuzha,Rural,Diebold,4.6,488,22,39.0,0,...,67,95,1,68,1,54,0,0,5,1
4,2025-01-05,ATM284,Thrissur,Hospital,NCR,8.7,736,25,57.0,0,...,54,56,3,97,4,57,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2025-12-22,ATM153,Kottayam,Airport,Diebold,8.1,595,29,69.0,0,...,58,177,0,79,3,5,0,0,1,1
49996,2025-12-23,ATM229,Kollam,Airport,Hitachi,7.3,578,11,85.0,1,...,67,41,3,77,3,70,6,1,0,0
49997,2025-12-24,ATM247,Thrissur,Hospital,Diebold,6.2,656,1,35.0,0,...,65,64,0,89,0,43,4,2,0,0
49998,2025-12-25,ATM184,Kottayam,Railway,NCR,1.9,471,19,62.0,0,...,71,114,0,100,1,0,2,3,1,1
49999,2025-12-26,ATM153,Palakkad,Hospital,Diebold,8.9,246,4,34.0,0,...,77,95,3,83,2,31,1,0,0,0

In [3]:
atm.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    50000 non-null  datetime64[us]
 1   ATM_ID                  50000 non-null  str
 2   District                50000 non-null  str
 3   Location_Type           50000 non-null  str
 4   Manufacturer            50000 non-null  str
 5   ATM_Age_Yrs             50000 non-null  float64
 6   Daily_Transactions      50000 non-null  int64
 7   Failed_Transactions     50000 non-null  int64
 8   Cash_Remaining_Pct      50000 non-null  float64
 9   Cash_Loaded_Today       50000 non-null  int64
 10  CardReader_Errors       50000 non-null  int64
 11  CashDispenser_Errors    50000 non-null  int64
 12  Cash_Jams               50000 non-null  int64
 13  Printer_Errors          50000 non-null  int64
 14  Paper_Remaining_Pct     50000 non-null  int64
 15  CPU_Temp_C              50000 non-null  float64
 16  CPU_Usage_Pct           50000 non-null  int64
 17  Memory_Usage_Pct        50000 non-null  int64
 18  Network_Latency_ms      50000 non-null  int64
 19  Network_Drops           50000 non-null  int64
 20  UPS_Battery_Pct         50000 non-null  int64
 21  Power_Outages_7D        50000 non-null  int64
 22  Days_Since_Maintenance  50000 non-null  int64
 23  Previous_Failures_90D   50000 non-null  int64
 24  Customer_Complaints_7D  50000 non-null  int64
 25  Failure_Code            50000 non-null  int64
 26  Failure_Next_48H        50000 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(19), str(4)
memory usage: 10.3 MB

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
atm['District'] = le.fit_transform(atm['District'])
atm['Location_Type'] = le.fit_transform(atm['Location_Type'])
atm['Manufacturer'] = le.fit_transform(atm['Manufacturer'])

In [7]:
X = atm.drop(columns=['ATM_ID', 'Date', 'Failure_Next_48H'])
y = atm['Failure_Next_48H']

In [8]:
X

,District,Location_Type,Manufacturer,ATM_Age_Yrs,Daily_Transactions,Failed_Transactions,Cash_Remaining_Pct,Cash_Loaded_Today,CardReader_Errors,CashDispenser_Errors,...,CPU_Usage_Pct,Memory_Usage_Pct,Network_Latency_ms,Network_Drops,UPS_Battery_Pct,Power_Outages_7D,Days_Since_Maintenance,Previous_Failures_90D,Customer_Complaints_7D,Failure_Code
0,2,2,2,1.2,429,15,69.0,0,2,3,...,29,52,46,0,78,2,29,4,1,5
1,6,4,0,1.9,343,6,43.0,0,0,3,...,50,45,10,0,92,3,58,1,0,2
2,7,0,0,2.5,285,10,78.0,0,2,1,...,65,53,66,2,88,0,63,0,0,0
3,0,5,0,4.6,488,22,39.0,0,2,2,...,84,67,95,1,68,1,54,0,0,5
4,9,2,2,8.7,736,25,57.0,0,2,2,...,74,54,56,3,97,4,57,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,5,0,0,8.1,595,29,69.0,0,1,3,...,32,58,177,0,79,3,5,0,0,1
49996,4,0,1,7.3,578,11,85.0,1,2,2,...,12,67,41,3,77,3,70,6,1,0
49997,9,2,0,6.2,656,1,35.0,0,1,0,...,49,65,64,0,89,0,43,4,2,0
49998,5,4,2,1.9,471,19,62.0,0,2,3,...,21,71,114,0,100,1,0,2,3,1
49999,8,2,0,8.9,246,4,34.0,0,2,0,...,43,77,95,3,83,2,31,1,0,0

In [9]:
y

0        1
1        1
2        0
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    0
Name: Failure_Next_48H, Length: 50000, dtype: int64

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
X_train

,District,Location_Type,Manufacturer,ATM_Age_Yrs,Daily_Transactions,Failed_Transactions,Cash_Remaining_Pct,Cash_Loaded_Today,CardReader_Errors,CashDispenser_Errors,...,CPU_Usage_Pct,Memory_Usage_Pct,Network_Latency_ms,Network_Drops,UPS_Battery_Pct,Power_Outages_7D,Days_Since_Maintenance,Previous_Failures_90D,Customer_Complaints_7D,Failure_Code
39087,0,1,2,5.4,601,17,37.0,0,0,3,...,25,65,72,1,100,0,5,1,2,5
30893,8,0,2,1.3,613,19,27.0,0,2,1,...,29,59,62,0,81,3,19,3,2,0
45278,5,4,0,9.5,337,8,49.0,1,1,3,...,33,67,33,4,90,3,50,0,0,5
16398,6,5,0,8.4,157,3,42.0,1,2,2,...,29,58,16,0,93,2,36,0,0,0
13653,8,0,0,1.9,422,15,76.0,0,0,3,...,26,57,82,1,83,0,41,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,9,4,0,4.8,346,1,45.0,0,1,0,...,64,61,35,0,99,4,24,0,1,0
44732,1,0,2,6.3,25,0,37.0,0,0,3,...,39,62,31,3,86,1,52,0,2,1
38158,7,5,0,9.3,699,9,79.0,0,1,3,...,67,83,74,0,100,0,44,0,0,2
860,7,1,1,9.2,336,0,46.0,1,2,3,...,53,39,39,0,87,0,65,0,0,1
15795,2,0,0,7.3,633,17,59.0,0,0,3,...,28,53,64,0,75,1,0,0,1,2

In [15]:
X_test

,District,Location_Type,Manufacturer,ATM_Age_Yrs,Daily_Transactions,Failed_Transactions,Cash_Remaining_Pct,Cash_Loaded_Today,CardReader_Errors,CashDispenser_Errors,...,CPU_Usage_Pct,Memory_Usage_Pct,Network_Latency_ms,Network_Drops,UPS_Battery_Pct,Power_Outages_7D,Days_Since_Maintenance,Previous_Failures_90D,Customer_Complaints_7D,Failure_Code
33553,0,4,1,2.2,493,14,55.0,1,0,0,...,35,74,68,2,80,4,57,1,3,0
9427,0,0,1,5.3,640,8,75.0,0,0,3,...,53,56,21,1,92,3,45,0,0,2
199,9,2,1,2.4,447,20,50.0,1,2,1,...,38,54,110,0,89,0,7,0,0,0
12447,6,2,2,5.8,490,11,28.0,0,1,1,...,40,50,17,2,100,1,17,2,0,0
39489,4,0,1,1.3,481,4,72.0,1,0,1,...,24,68,80,1,86,0,33,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28567,2,5,1,4.9,479,4,56.0,0,1,2,...,48,55,61,2,96,3,40,1,0,0
25079,4,0,2,5.6,425,0,62.0,0,2,0,...,35,50,42,0,98,1,68,6,4,6
18707,1,4,1,8.8,281,9,43.0,0,1,3,...,35,56,133,2,77,0,22,0,2,3
15200,8,5,1,3.4,376,7,86.0,0,1,2,...,47,72,59,1,83,0,17,0,0,0
5857,7,4,2,5.8,78,3,29.0,0,2,2,...,42,47,87,1,84,0,36,0,2,0

In [16]:
y_train

39087    1
30893    0
45278    1
16398    0
13653    1
        ..
11284    0
44732    1
38158    1
860      1
15795    1
Name: Failure_Next_48H, Length: 40000, dtype: int64

In [17]:
y_test

33553    0
9427     1
199      0
12447    0
39489    0
        ..
28567    0
25079    1
18707    1
15200    0
5857     0
Name: Failure_Next_48H, Length: 10000, dtype: int64

In [18]:
atm['ATM_ID'].unique()

<StringArray>
['ATM058', 'ATM173', 'ATM187', 'ATM256', 'ATM284', 'ATM272', 'ATM109',
 'ATM068', 'ATM230', 'ATM285',
 ...
 'ATM296', 'ATM132', 'ATM014', 'ATM283', 'ATM188', 'ATM254', 'ATM033',
 'ATM057', 'ATM225', 'ATM271']
Length: 300, dtype: str

In [19]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
X_train_scaled

array([[-1.56777311, -0.86396953,  1.21730706, ..., -0.04699399,
         0.69937635,  1.68791994],
       [ 1.21956491, -1.44916606,  1.21730706, ...,  1.42271631,
         0.69937635, -0.71228474],
       [ 0.17431315,  0.89162006, -1.23163336, ..., -0.78184913,
        -0.78494763,  1.68791994],
       ...,
       [ 0.87114766,  1.4768166 , -1.23163336, ..., -0.78184913,
        -0.78494763,  0.24779713],
       [ 0.87114766, -0.86396953, -0.00716315, ..., -0.78184913,
        -0.78494763, -0.2322438 ],
       [-0.87093861, -1.44916606, -1.23163336, ..., -0.78184913,
        -0.04278564,  0.24779713]], shape=(40000, 24))

In [21]:
X_test_scaled

array([[-1.56777311,  0.89162006, -0.00716315, ..., -0.04699399,
         1.44153834, -0.71228474],
       [-1.56777311, -1.44916606, -0.00716315, ..., -0.78184913,
        -0.78494763,  0.24779713],
       [ 1.56798216, -0.278773  , -0.00716315, ..., -0.78184913,
        -0.78494763, -0.71228474],
       ...,
       [-1.21935586,  0.89162006, -0.00716315, ..., -0.78184913,
         0.69937635,  0.72783807],
       [ 1.21956491,  1.4768166 , -0.00716315, ..., -0.78184913,
        -0.78494763, -0.71228474],
       [ 0.87114766,  0.89162006,  1.21730706, ..., -0.78184913,
         0.69937635, -0.71228474]], shape=(10000, 24))

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn = KNeighborsClassifier(n_neighbors=5)

In [24]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [25]:
y_pred = knn.predict(X_test_scaled)
y_pred

array([0, 0, 0, ..., 1, 0, 0], shape=(10000,))

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
print('Accuracy Score:', accuracy_score(y_test, y_pred)*100)

Accuracy Score: 92.75

In [28]:
accuracy_scores=[]
# Test k values from 1 to 20
for k in range(1,21):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled,y_train)
    y_pred=knn.predict(X_test_scaled)
    accuracy_scores.append(accuracy_score(y_test,y_pred))
accuracy_scores

[0.8901,
 0.8691,
 0.9205,
 0.8961,
 0.9275,
 0.909,
 0.9313,
 0.9139,
 0.9353,
 0.916,
 0.9367,
 0.9212,
 0.9378,
 0.923,
 0.9387,
 0.9254,
 0.9397,
 0.9272,
 0.9394,
 0.9287]

In [29]:
best_k = np.argmax(accuracy_scores)+1
best_k

np.int64(17)

In [30]:
print('The best value for k:', best_k)

The best value for k: 17

In [31]:
knn_final = KNeighborsClassifier(n_neighbors = best_k)

In [32]:
knn_final.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=np.int64(17))

In [33]:
y_pred_final = knn_final.predict(X_test_scaled)
y_pred_final

array([0, 1, 0, ..., 1, 0, 0], shape=(10000,))

In [34]:
print('Final Model Accuracy:', accuracy_score(y_test,y_pred_final)*100)

Final Model Accuracy: 93.97

In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [36]:
accuracy = accuracy_score(y_test, y_pred_final)
accuracy

0.9397

In [37]:
precision = precision_score(y_test, y_pred_final, average = 'weighted')
precision

0.9453260304968262

In [38]:
recall = recall_score(y_test, y_pred_final, average = 'weighted')
recall

0.9397

In [39]:
f1 = f1_score(y_test, y_pred_final, average = 'weighted')
f1

0.9389795490235132

In [40]:
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.9397
Precision: 0.9453260304968262
Recall   : 0.9397
F1 Score : 0.9389795490235132

- The KNN classifier achieved an accuracy of 93.97%, indicating high prediction performance.
- The precision of 94.53% shows that most predicted failures are correct.
- The recall of 93.97% indicates that the model successfully detects most actual ATM failures.
- The F1-score of 93.90% demonstrates a good balance between precision and recall.
- Overall, the KNN model performs well and is suitable for ATM failure prediction.

In [41]:
from sklearn.metrics import classification_report

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      1.00      0.94      5669
           1       1.00      0.84      0.91      4331

    accuracy                           0.93     10000
   macro avg       0.94      0.92      0.93     10000
weighted avg       0.94      0.93      0.93     10000

### 1. Class 0 (No Failure)
- The model achieved a precision of 0.89, meaning that 89% of the ATMs predicted as "No Failure" were actually non-failing ATMs.
- The recall of 1.00 indicates that the model successfully identified all actual non-failure cases without missing any.
- The F1-score of 0.94 shows excellent performance in classifying non-failure cases.
### 2. Class 1 (Failure)
- The model achieved a precision of 1.00, meaning every ATM predicted as a failure was truly a failure. There were essentially no false positive predictions for this class.
- The recall of 0.84 indicates that the model correctly detected 84% of the actual failures, while approximately 16% of failure cases were missed.
- The F1-score of 0.91 demonstrates strong performance in identifying failure cases.